### ISSUE TITLE
[BUG] Start Markers return as tiles after exiting/reentering World

### ISSUE THREAD

**Issue by jobras85** [kckaiwei/TurnMarker-alt#32]
To recreate:
- Enable Turn Marker mod
- Enable Start Marker (I'm using bluesky.png asset)
- Begin combat, move tokens for each of their turns
- End combat (at this point, the start markers will be gone)
- Exit World/ Log Out
- Re-enter World
- Start Markers will reappear for every turn for every actor, showing up as "Tiles" which can then be deleted. They are visible and cause some lag. 

![Results - Start Markers shows up as Tiles upon reloading World](https://user-images.githubusercontent.com/32499983/104973808-2d5cb300-59b3-11eb-8686-b9eeb2a4d4d3.PNG)
![Settings 1](https://user-images.githubusercontent.com/32499983/104973809-2e8de000-59b3-11eb-963d-c3160f8c3c9b.PNG)
![Settings 2](https://user-images.githubusercontent.com/32499983/104973810-2f267680-59b3-11eb-98d6-a861b4cda14a.PNG)
![Settings 3](https://user-images.githubusercontent.com/32499983/104973812-2f267680-59b3-11eb-96fd-a909496e142e.PNG)

**Comment by kckaiwei** [comment]
Ok, I'll try to recreate it once I'm free.

Also, which version of turnmarker are you using? This is only on rejoining? It's not happening normally anymore? There used to be a bug where it'd stick around randomly during a game that was resolved in 2.7.2

**Comment by jobras85** [comment]
Good question. I was using 2.6.9. Not sure why, but it wasn't auto-updating past that when I would update through the mod page in Foundry. So I uninstalled, re-installed, and was able to get to the current 2.7.2 version. Now I cannot (currently) recreate the bug. For now, this can be closed. 

Thanks for pointing out the obvious. Sorry for the false alarm! 

![Version 2 6 9](https://user-images.githubusercontent.com/32499983/104979689-1d000480-59c2-11eb-8f8b-8d78762b6bf4.PNG)

**Comment by kckaiwei** [comment]
Okay, that's great to hear!
