### ISSUE TITLE
Full /src/ directory included in Released Zip

### ISSUE THREAD

**Issue by Aeristoka** [kckaiwei/TurnMarker-alt#36]
Full /src/ directory included in Released Zip, causing the module to appear as if it is multiple modules (one at the root of the zip, as is proper, an additional one inside the /src/ folder.

**Comment by kakaroto** [comment]
More specifically, this is causing an issue with The Forge's Bazaar which once it downloads the zip, it does not know which of the two folders it needs to extract and install as the module, as it sees two module.json and therefore thinks there are two modules in the zip, so it does not add the 2.7.3 release to the Bazaar.

**Comment by kckaiwei** [comment]
Yeah, let me update that. I don't remember having a src in there when I packaged it, but I guess I screwed up somewhere.

**Comment by kckaiwei** [comment]
Ok, it's been updated and I've downloaded the zip to confirm. Thanks for bringing this to my attention.

**Comment by Aeristoka** [comment]
Awesome! Thanks.
