### ISSUE TITLE
Hidden Name CUB support

### ISSUE THREAD

**Issue by Kayne** [kckaiwei/TurnMarker-alt#46]
Would be nice if TurnMarker start supporting CUB Hidden Name funcionality. It works great with multiple modules, sadly, TurnMarker's round announcement displays token name plain in sight. CUB hides name with "Unknow Creature" or any other string user defines in CUB settings.

**Comment by kckaiwei** [comment]
There is an option in the settings to hide creature names (but show player names, obviously). I think that would suit your use case fine, but I can take a look into CUB.

**Comment by Kayne** [comment]
Oh, is it? That would definetely work for me! Where excatly can I find this setting? I was looking for that but I didn't find anything. This is how TurnMarker looks for me and there is nothing about hiding creature name:
<img width="577" alt="Zrzut ekranu 2021-02-10 o 09 43 34" src="https://user-images.githubusercontent.com/1120451/107485838-9a173780-6b84-11eb-9203-4b62e0e66ef8.png">
<img width="485" alt="Zrzut ekranu 2021-02-10 o 09 43 55" src="https://user-images.githubusercontent.com/1120451/107485854-a00d1880-6b84-11eb-87f4-c1b36279be86.png">

**Comment by kckaiwei** [comment]
![image](https://user-images.githubusercontent.com/12780629/110559799-e23d6180-8112-11eb-9e3b-6455d5bfa223.png)

It's the one for "Use Token Name to Announce". If it's not there, you might need to update your version of TurnMarker.

**Comment by Kayne** [comment]
Ok, now I see what happend. I think there was somekind of weird repository change or something for Turn Marker, because I see  that I have the latest version (2.6.9), since it doesn't updated when I click update button. When I go to repository page of my installed Turn Marker (I was installing from modules library) the URL is https://github.com/Brunhine/TurnMarker.

However in the modules library window the latest version is 2.7.3 and repository is different: https://github.com/kckaiwei/TurnMarker-alt

So, what happened? Why did repository changed?
And on the side note, why did it change in Modules Installation window and didn't change for already installed modules? I know it's more of the Foundry VTT issue actually, but nevertheless, there wouldn't be any issue if module manifest URL would update as well.

Anyhow, I think the mystery was solved.
