### ISSUE TITLE
[FEATURE] Hide names of enemies in chat

### ISSUE THREAD

**Issue by kenpoh01** [kckaiwei/TurnMarker-alt#52]
Hello,  
First of all great module. 
I was wondering if there was a way to disable the names of the enemies in chat when their turn comes up.  I know I can turn this off completely for all actors, so nothing comes up in chat, but it would be great to keep it on, and for it just to say "unknown creature" instead of it's name.  I have CUB hiding the names of creatures everywhere else but it doesn't work on with this module.

Thanks

**Comment by kckaiwei** [comment]
Yeah, let me look into how CUB (combat utility belt) is doing it, and see if I can make it work. Otherwise, there is a drop down for hiding certain names from a certain actors, such as all GM controlled, etc. It doesn't let you hide specific actors, but if I can get it to hook/work with CUB, then it may be possible then.

**Comment by kckaiwei** [comment]
<img width="760" alt="Screen Shot 2021-05-01 at 6 29 14 PM" src="https://user-images.githubusercontent.com/12780629/116796536-27469a00-aaab-11eb-877e-48634f04f189.png">

I may need some more information about this @kenpoh01 . The attached screenshot is CUB + turnmarker only, on 5e. I've made 2 PCs and 1 NPC (hostile), and have hide hostile names. It seems to work as intended, unless I'm misunderstanding what you want it to show.

**Comment by kenpoh01** [comment]
Hmm, maybe I had a conflict with another module.  My players were telling me they could see the names in chat from Turn Marker, but now it seems to be working at my end too.  Sorry about that.

**Comment by kckaiwei** [comment]
Not a problem, if it happens again, feel free to make a new issue, and if possible steps to reproduce.
