### ISSUE TITLE
Add new pack #77

### ISSUE THREAD

**Issue by brunocalado** [kckaiwei/TurnMarker-alt#62]
Hi.

A friend <https://www.facebook.com/groups/379533023004717/user/100000544281866/> or <https://github.com/cefasheli> offered some of his work, but it's webm.

- [ ]  Add the pack in the zip

Thank you for the great module.
[turnmaker.zip](https://github.com/kckaiwei/TurnMarker-alt/files/6487011/turnmaker.zip)

**Comment by kckaiwei** [comment]
It looks amazing, but I don't think I can use this. I would need to get explicit permission from him for licensing, and an original image would be preferred, Foundry doesn't have direct support for webm, iirc. I may be able to convert it to a .gif, but I'd still need to get his permission for it directly. I don't think hearsay works for licensing.

**Comment by brunocalado** [comment]
I can ask him to talk to you.

But, about that part of the conversion I can help.
