### ISSUE TITLE
Weird things going on

### ISSUE THREAD

**Issue by TheFabulousIronChef** [kckaiwei/TurnMarker-alt#75]
#1 When I end combat, the "on deck" turn marker remains and then cannot be deleted, giving a weird error messages. Two screenshots depicting Issue #1 and Issue #2. 

#2 I have some kind of weird dots rotating around instead of the rotating turn marker. Not sure why that is. Another module, perhaps? 

![Screen Shot 2021-06-26 at 6 14 23 PM](https://user-images.githubusercontent.com/46587602/123527112-d5854f00-d6aa-11eb-9906-1fb33581022e.png)
![Screen Shot 2021-06-26 at 6 14 51 PM](https://user-images.githubusercontent.com/46587602/123527116-d918d600-d6aa-11eb-9d2d-d436ec99d67e.png)

**Comment by duckpuppy** [comment]
I can help with one of those... the rotating dots is Monk's Little Details / Combat Token Highlight

**Comment by cedwards4** [comment]
I am also having the same problem as the first issue. Any solution?

**Comment by Nedrapter** [comment]
Same, having the error messages and markers stay after combat , impossible to delete.

**Comment by kckaiwei** [comment]
Should be fixed in the recently merged/released #81
