### ISSUE TITLE
Only DM can see Turn Marker

### ISSUE THREAD

**Issue by Masterfuzzfuzz** [kckaiwei/TurnMarker-alt#79]
Pretty self explanatory. Everything works fine for DM. Players get sound notifications, but no turn marker animation is playing.

**Comment by LordMallus** [comment]
Can confirm this as well.  Just started using Foundry and the turn marker and only I could see the marker as GM.

**Comment by RuebenMF** [comment]
Also getting this issue

**Comment by CKarper** [comment]
I've been getting this ever since upgrade Foundry 0.8.x

**Comment by ShiftyRat** [comment]
Same issue as well.

**Comment by SlothManJ** [comment]
Same issue still, Wondering if anyone has figured out a solution?

**Comment by markjfisher** [comment]
This is a copy of #70 where there's a merge request waiting to fix this (#77)

**_Warning!_**

The following (for me) only partially works, and I'm seeing a lot of visual issues running a patched version of TurnMarker in the latest Foundry (0.8.9) with latest DnD5e (1.5.2) rules.

With that warning aside, you can manually patch the problem on your local Foundry while waiting for the update. This is needed on the server:

1. In Windows press <windows key>-R
2. Type "%localappdata%" in the box (no quotes) and hit enter
3. Open folder: "FoundryVTT/Data/modules/turnmaker/scripts"
4. Edit "turnmaker.js" is a decent text editor (suggest Notepad++)
5. Go to line 169 and change "tokenId" to "token.id"  (this is the only change in the merge request)
6. Save and close the file
7. In Foundry VTT server and client just need to refresh the application with F5

You should see the turn marker now.

However!! I am seeing a lot of other bugs testing this in latest Foundry (marker not moving to correct place, marker not starting in correct place, players seeing markers after combat finished which can't be deleted, and other issues), so I would suggest waiting for a full tested fix if this module is still active.

**Comment by kckaiwei** [comment]
Should be resolved in the latest release.
