### ISSUE TITLE
Marker out of place / misaligned

### ISSUE THREAD

**Issue by BlackWand1** [kckaiwei/TurnMarker-alt#80]
It happens rather often that the marker is aligned with the pc/npc incorrectly. Sometimes just a block while other times way of.
I think it happens more often when you have more creatures on the scene that is part of combat.

![Turn Marker](https://user-images.githubusercontent.com/85252943/132958524-b998a59e-e4cf-4dbe-973d-d5f6eee23ffe.PNG)

**Comment by kckaiwei** [comment]
Should be fixed on the recent release, closing for now.
